### ISSUE TITLE
Project 5 resource resource method focused on the lecture

### ISSUE THREAD

**Issue by joanplaja** [pattonsgirl/Spring2022-CEG3120#9]
Hello i'm the author of https://blog.devgenius.io/build-your-first-ci-cd-pipeline-using-docker-github-actions-and-webhooks-while-creating-your-own-da783110e151 is this a project for university students ?
I just found that you used my medium article and i was super excited about it.

**Comment by pattonsgirl** [comment]
Hello!  Yes, it is.  Your article did a great job walking through the core steps!
